### ISSUE TITLE
目录扫描功能由于没有正确处理URL导致程序退出

### ISSUE THREAD

**Issue by panzhen1992** [qiwentaidi/Slack#1]
目录扫描，输入URL后，工具闪退

**Comment by qiwentaidi** [comment]
是否是url中存在一些不可见字符，例如是\r这种，可以看看log下面的日志吗

**Comment by panzhen1992** [comment]
点击开始任务就会闪退
![image](https://github.com/qiwentaidi/Slack/assets/63719033/605c8072-8be8-48c6-b3b8-1388727b5d36)

**Comment by qiwentaidi** [comment]
我此处没有做这种特殊字符过滤以及最后的url的/处理，你麻烦在末尾加个/ 例如http://www.baidu.com/再试试

**Comment by panzhen1992** [comment]
解决了，感谢

**Comment by qiwentaidi** [comment]
已在1.4.2版本中修复
