### ISSUE TITLE
目录扫描状态码过滤无效

### ISSUE THREAD

**Issue by onewinner** [qiwentaidi/Slack#10]
![image](https://github.com/qiwentaidi/Slack/assets/94044430/875fc5f0-185a-4932-9c00-480b063aef89)
![image](https://github.com/qiwentaidi/Slack/assets/94044430/94126421-26ba-4361-bb81-4cbe5e12f376)

**Comment by qiwentaidi** [comment]
不好意思这个功能忘记写了，光做了界面，下个版本修复

**Comment by qiwentaidi** [comment]
新版代码中已做修复
![image](https://github.com/qiwentaidi/Slack/assets/104491549/90ae48f7-b476-4f0f-8464-f4847c7a4f81)
