### ISSUE TITLE
端口扫描IP地址格式化不严格，可能导致命令执行

### ISSUE THREAD

**Issue by nonu11** [qiwentaidi/Slack#12]
由于地址格式化不严格，引入恶意IP地址，开启存活探测模式时（默认配置关闭），可拼接导致命令执行（windows下v1.4.7版本）
![图片](https://github.com/qiwentaidi/Slack/assets/17950878/5efad6ac-eed3-4c54-9dd6-9ecb40647306)
![图片](https://github.com/qiwentaidi/Slack/assets/17950878/7d336b80-9202-47a4-848c-6e0cd2904a36)

**Comment by qiwentaidi** [comment]
<img width="831" alt="image" src="https://github.com/qiwentaidi/Slack/assets/104491549/242207f7-2e0b-4e31-8774-3e209de1df12">
![image](https://github.com/qiwentaidi/Slack/assets/104491549/deff41d5-9ba4-4f6d-8310-dce9bfdb0662)
新版代码中增加了ipv4校验，已修复
