### ISSUE TITLE
Macos 14.3 M2 端口扫描结果无法导出和复制

### ISSUE THREAD

**Issue by wuha0926** [qiwentaidi/Slack#13]
Macos 14.3 M2 端口扫描结果无法导出和复制

**Comment by qiwentaidi** [comment]
新版代码中已经修复该问题，这个导出问题是专门针对macos才会发生，目前使用原生dialog组件替换xlsx自带的导出功能，复制功能也已修复
<img width="1191" alt="image" src="https://github.com/qiwentaidi/Slack/assets/104491549/c90b7b7b-af2b-4751-9a4a-401ef31d2e51">
