### ISSUE TITLE
几点小tips

### ISSUE THREAD

**Issue by onewinner** [qiwentaidi/Slack#20]
1、在线导航，建议加一个自定义编辑选项，想到这界面突然有个新奇想法，就是本地文件工具启动，哈哈
2、联想字典生成器，建议把生成字典的规则展示在旁边允许自定义更改规则
3、备忘录反弹shell模块，可以集成这个项目https://github.com/0dayCTF/reverse-shell-generator （我看加解密集成了CyberChef，哦对，在远程加载CyberChef希望能支持工具本身设置的代理，不然每次访问都得开系统代理）
4、看到新版本也搞了漏洞利用模块哈哈，能否先加个nacos的那几个洞

**Comment by qiwentaidi** [comment]
1、2、4点都可以实现，3我觉得没什么必要，一个是因为在iframe首先本身不支持代理操作，再是因为有本地加载的功能，我觉得真的有需要的话下载到本地启用是最优解，已经编译好的项目就20多MB。

**Comment by qiwentaidi** [comment]
> 1、2、4点都可以实现，3我觉得CyberChef设置代理没什么必要，一个是因为在iframe首先本身不支持代理操作，再是因为有本地加载的功能，我觉得真的有需要的话下载到本地启用是最优解，已经编译好的项目就20多MB。

**Comment by qiwentaidi** [comment]
<img width="1280" alt="image" src="https://github.com/qiwentaidi/Slack/assets/104491549/5aac1500-6493-46cd-bda0-cdac53ee1954">
反弹shell已实装

**Comment by onewinner** [comment]
太强了，哈哈哈，那个CyberChef下载本地加载报404，一直没试成功
![image](https://github.com/qiwentaidi/Slack/assets/94044430/1c826f17-17f4-4814-abfb-4566eb1de481)

**Comment by qiwentaidi** [comment]
> 太强了，哈哈哈，那个CyberChef下载本地加载报404，一直没试成功 ![image](https://private-user-images.githubusercontent.com/94044430/335841137-1c826f17-17f4-4814-abfb-4566eb1de481.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTczMzY1NjksIm5iZiI6MTcxNzMzNjI2OSwicGF0aCI6Ii85NDA0NDQzMC8zMzU4NDExMzctMWM4MjZmMTctMTdmNC00ODE0LWFiZmItNDU2NmViMWRlNDgxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjAyVDEzNTEwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUxMGQ3OWYwYmM5MmExOTRhYzE2YTM3NjM3MDlkZDNkYTA3NTkzYTRhZTE0NjlmNWVkNjk5OTNkZTQ2ZGYwYjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.B0RBn3q1-75DJ151nfCLXIGCKhF8puzjT55m2EpzyI8)

还真是404等我看看是哪里的问题，晚点重新弄一版

**Comment by qiwentaidi** [comment]
> 太强了，哈哈哈，那个CyberChef下载本地加载报404，一直没试成功 ![image](https://private-user-images.githubusercontent.com/94044430/335841137-1c826f17-17f4-4814-abfb-4566eb1de481.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTczMzY1NjksIm5iZiI6MTcxNzMzNjI2OSwicGF0aCI6Ii85NDA0NDQzMC8zMzU4NDExMzctMWM4MjZmMTctMTdmNC00ODE0LWFiZmItNDU2NmViMWRlNDgxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjAyVDEzNTEwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUxMGQ3OWYwYmM5MmExOTRhYzE2YTM3NjM3MDlkZDNkYTA3NTkzYTRhZTE0NjlmNWVkNjk5OTNkZTQ2ZGYwYjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.B0RBn3q1-75DJ151nfCLXIGCKhF8puzjT55m2EpzyI8)

已修复，问题出现在defaultPath的值最后没有加/问题，导致目录拼接错误
<img width="527" alt="image" src="https://github.com/qiwentaidi/Slack/assets/104491549/776d210e-1f15-4ae7-85d6-8a1de519ce88">

**Comment by qiwentaidi** [comment]
> 1、在线导航，建议加一个自定义编辑选项，想到这界面突然有个新奇想法，就是本地文件工具启动，哈哈 2、联想字典生成器，建议把生成字典的规则展示在旁边允许自定义更改规则 3、备忘录反弹shell模块，可以集成这个项目https://github.com/0dayCTF/reverse-shell-generator （我看加解密集成了CyberChef，哦对，在远程加载CyberChef希望能支持工具本身设置的代理，不然每次访问都得开系统代理） 4、看到新版本也搞了漏洞利用模块哈哈，能否先加个nacos的那几个洞

关于在线导航这个模块，其实让用户自定义不是非常方便，做的时候涉及到组的中英文名称显示，还有后续加载的LOGO（目前都是本地保存），我觉得后续有什么好用的可以提出来加一下，毕竟咱们已经有了浏览器自己的书签了，这个在线主要是加给一些比较常用的，大众使用频率较高的
<img width="917" alt="image" src="https://github.com/qiwentaidi/Slack/assets/104491549/be5d264c-1b2c-4ee2-bb15-4e40db4db2d8">

**Comment by onewinner** [comment]
嗯嗯了解，像gowails可以应该可以写本地工具启动器吧，比如一些java、python之类的点击写一下执行cmd命令启动、或者启动命令行窗口

**Comment by qiwentaidi** [comment]
> 嗯嗯了解，像gowails可以应该可以写本地工具启动器吧，比如一些java、python之类的点击写一下执行cmd命令启动、或者启动命令行窗口

这个可以实现，之前用fyne做过一个类似的，后面发现有rolan的项目可以用破解，然后还有everything和listary这种全局搜索的应用，像java启动的gui程序直接搜到点击就可以启用了，后面代码就被我删掉了，我觉得集成在应用里面的话使用性不是很高

**Comment by qiwentaidi** [comment]
字典这块把能操作的规则都加上了，主要本身生成的规则就不咋多，可控参数也不多，就先这样了，后续有好的想法再升级
<img width="1280" alt="image" src="https://github.com/qiwentaidi/Slack/assets/104491549/7a71d687-5594-4948-8e65-5ac3ae7a894c">

**Comment by qiwentaidi** [comment]
<img width="1280" alt="image" src="https://github.com/qiwentaidi/Slack/assets/104491549/ef9ccb46-0ed0-4263-b630-c798685e59a2">
本地工具启动有个测试版，代码已经发布，可以测试一下功能

**Comment by qiwentaidi** [comment]
除了Nacos，其他都已完毕，漏洞利用的模块暂时搁置
