### ISSUE TITLE
目录扫描状态码过滤bug

### ISSUE THREAD

**Issue by onewinner** [qiwentaidi/Slack#21]
之前提过一次，但好像设置后还是没生效
![image](https://github.com/qiwentaidi/Slack/assets/94044430/726f6149-df8e-42b2-95c1-ce5a043c1292)
![image](https://github.com/qiwentaidi/Slack/assets/94044430/01c66378-b2fb-497d-829c-57e43cdd1c8b)

**Comment by onewinner** [comment]
这里的过滤逻辑是筛选还对应状态码、还是排除对应状态，总感觉有点问题

**Comment by qiwentaidi** [comment]
> 这里的过滤逻辑是筛选还对应状态码、还是排除对应状态，总感觉有点问题

这里实际是排除状态码

**Comment by qiwentaidi** [comment]
> 这里的过滤逻辑是筛选还对应状态码、还是排除对应状态，总感觉有点问题

有我vx吗，可以vx聊

**Comment by qiwentaidi** [comment]
1.5.3版本也已经修复这个，状态码排除显示填入的
