### ISSUE TITLE
1.5.3M2芯片下闪退

### ISSUE THREAD

**Issue by fliggyaa** [qiwentaidi/Slack#22]
1.5.3在m2芯片的mbp打开之后闪退

**Comment by qiwentaidi** [comment]
我本地同样m2芯片无法复现

**Comment by qiwentaidi** [comment]
1.5.2会闪退吗

**Comment by qiwentaidi** [comment]
1.5.2会闪退吗

**Comment by qiwentaidi** [comment]
同[issue16](https://github.com/qiwentaidi/Slack/issues/16)由于新版加入联动模块后，要默认加载网站扫描路由，会触发这个问题

**Comment by fliggyaa** [comment]
不知道，我现在用的是1.4.9

**Comment by qiwentaidi** [comment]
> 不知道，我现在用的是1.4.9

项目已经重新发布了一版，试一下

**Comment by qiwentaidi** [comment]
有我联系方式吗，加一下給你个测试版再帮忙测测

**Comment by fliggyaa** [comment]
fliggy0_0  wechat
