### ISSUE TITLE
windows11 打开闪退

### ISSUE THREAD

**Issue by ByZain** [qiwentaidi/Slack#23]
上个版本使用正常，新版闪退

**Comment by qiwentaidi** [comment]
与issues22一致，目前怀疑是创建字典的问题，正在恢复上版本代码重试

**Comment by qiwentaidi** [comment]
同[issue16](https://github.com/qiwentaidi/Slack/issues/16)由于新版加入联动模块后，要默认加载网站扫描路由，会触发这个问题

**Comment by qiwentaidi** [comment]
重新发布了一版试试

**Comment by qiwentaidi** [comment]
新版代码中已修复
