### ISSUE TITLE
nuclei 无法加载 M1 mbp

### ISSUE THREAD

**Issue by China-natian** [qiwentaidi/Slack#24]
<img width="1280" alt="image" src="https://github.com/user-attachments/assets/0640111e-5dc5-406c-87c9-fd2281aeaac4">
检测引擎可以,重启或者重载(reload engine)都试过,无法完成漏洞扫描
<img width="1280" alt="image" src="https://github.com/user-attachments/assets/3b93b18f-00e2-4099-90c1-5af814665c12">

**Comment by qiwentaidi** [comment]
我觉得是显示引擎bug，实际你重启只会是能检测到的，如果解决不了的话加一下我vx
<img width="1280" alt="image" src="https://github.com/user-attachments/assets/0ffca294-ec33-450d-9f26-3084688a5895">
<img width="1280" alt="image" src="https://github.com/user-attachments/assets/9e883e29-b676-44b5-ba00-d0970ae4f3d6">

**Comment by qiwentaidi** [comment]
我能复现这个问题，无法选择漏洞扫描和指纹漏洞扫描，下个版本会修复

**Comment by qiwentaidi** [comment]
<img width="1280" alt="image" src="https://github.com/user-attachments/assets/550cc2f2-8a72-4675-8095-bc66e2ff0cd2">
今天预计会上新版，更新会修复

**Comment by qiwentaidi** [comment]
新版已经发布，修复完成
