### ISSUE TITLE
打包问题

### ISSUE THREAD

**Issue by blockmood** [qiwentaidi/Slack#25]
我是mac环境  正常执行wails build 打包没有问题

为什么我执行wails build -platform windows/arm64 就会报错呢

![image](https://github.com/user-attachments/assets/fda69c6e-6f6e-46fd-98e1-6e1cca3972a2)

**Comment by blockmood** [comment]
@qiwentaidi

**Comment by qiwentaidi** [comment]
你自身是amd架构的系统吧，目前情况来看macos只能在arm系统下进行 arm/amd的双平台编译，因为程序涉及到gcc库的调用。不同架构gcc的内容会有差别

**Comment by blockmood** [comment]
@qiwentaidi  我是macm3的

**Comment by qiwentaidi** [comment]
奥，系统无法跨平台打包，需要到对应的主机系统才行

**Comment by qiwentaidi** [comment]
原因跟上述说的一样，是因为gcc库的限制

**Comment by blockmood** [comment]
@qiwentaidi  明白了 谢了
