### ISSUE TITLE
mac下启动失败

### ISSUE THREAD

**Issue by 1nformation** [qiwentaidi/Slack#3]
<img width="1002" alt="image" src="https://github.com/qiwentaidi/Slack/assets/93757156/0c83ad7f-03cd-4414-8888-1720162c50a4">

inter芯片

**Comment by qiwentaidi** [comment]
有点奇怪，其他mac用户是能打开的

**Comment by qiwentaidi** [comment]
你可以尝试一下从源码启动吗
