### ISSUE TITLE
导出文件空白

### ISSUE THREAD

**Issue by mortal-sec** [qiwentaidi/Slack#30]
![image](https://github.com/user-attachments/assets/5578ec90-663b-4e81-ae5d-4913a36e6903)
![image](https://github.com/user-attachments/assets/a4f13e05-5278-41aa-a790-8330a0717800)
导出文件经常出现空白

**Comment by qiwentaidi** [comment]
感谢师傅的提议，目前看来是代码在进行FOFA查询遇到错误时会直接return退出，异步处理是没正确返回报错或者提示信息，导致数据导出为空且用户无感知，目前已做更改
<img width="977" alt="image" src="https://github.com/user-attachments/assets/06fcc740-c6b4-498b-834c-5d7ebc2489b5">

**Comment by mortal-sec** [comment]
感谢师傅这么快的处理，就是无感导出空白，hunter和数字厂商的功能点好像也是这样子，麻烦师傅排查一下

**Comment by qiwentaidi** [comment]
1.6.6版本已经修复该问题，师傅可测试一下

**Comment by mortal-sec** [comment]
> 1.6.6版本已经修复该问题，师傅可测试一下

目前测试已经可以了，感谢师傅
