### ISSUE TITLE
考虑 asynq 分布式?

### ISSUE THREAD

**Issue by zhihuba** [qiwentaidi/Slack#31]
考虑 asynq 分布式?

**Comment by qiwentaidi** [comment]
我不是很懂分布式的理念，可以简单描述一下c端应用在做了分布式之后有什么效果吗

**Comment by qiwentaidi** [comment]
如果只是要网站扫描功能拆分可以看，[Slack webscan cli](https://github.com/qiwentaidi/initial)

**Comment by zhihuba** [comment]
thank 抽空改改
