### ISSUE TITLE
子域名查询闪退

### ISSUE THREAD

**Issue by timetravel-boy** [qiwentaidi/Slack#34]
配置了API，输域名点击开始任务就闪退

**Comment by qiwentaidi** [comment]
已修复，由于FOFA前面查询的时候传入了nil，会导致查询出错，先暂停使用fofa查询子域名模块即可，下个版本更新发布
<img width="734" alt="image" src="https://github.com/user-attachments/assets/988403e3-3439-4e8a-99fc-cfee128fe3f2">

**Comment by timetravel-boy** [comment]
太肝了，表哥，新问题又来了，查询单位这样的，不知道怎么回事
![image](https://github.com/user-attachments/assets/fed8828d-1cbd-40c7-a7e9-f3cb1a28d05e)

**Comment by qiwentaidi** [comment]
其他单位信息查询也这样吗，还是就某个单位，注意查看自己账号是否被封禁



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年11月19日(周二) 上午9:53
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [qiwentaidi/Slack] 子域名查询闪退 (Issue #34)




 
太肝了，表哥，新问题又来了，查询单位这样的，不知道怎么回事
 image.png (view on web)

**Comment by qiwentaidi** [comment]
1.7.3已修复该问题
