### ISSUE TITLE
rdp协议识别错误

### ISSUE THREAD

**Issue by lesssafe** [qiwentaidi/Slack#37]
在端口扫描的时候rdp协议会识别为https
<img width="1280" alt="image" src="https://github.com/user-attachments/assets/85b549b8-eaa6-485e-86d8-7d6037ad4a55" />

**Comment by qiwentaidi** [comment]
<img width="592" alt="image" src="https://github.com/user-attachments/assets/011cb198-478d-430b-929c-ce3dafb23cd5" />
问题代码，下个版本会修复

**Comment by qiwentaidi** [comment]
1.7.6已修复
