### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by timetravel-boy** [qiwentaidi/Slack#6]
..\..\go\pkg\mod\github.com\wailsapp\wails\v2@v2.7.1\pkg\templates\templates.go:27:12: pattern all:ides/*: no matching files found

**Comment by qiwentaidi** [comment]
能提供一下系统或者其他信息吗

**Comment by timetravel-boy** [comment]
> 能提供一些系统或者其他信息吗

就在windows安装： go install github.com/wailsapp/wails/v2/cmd/wails@latest报错呢

**Comment by qiwentaidi** [comment]
> > 能提供一些系统或者其他信息吗
> 
> 就在windows安装： go install github.com/wailsapp/wails/v2/cmd/wails@latest报错呢

是不是你的Go的版本问题，用go get试试

**Comment by timetravel-boy** [comment]
> > > 能提供一些系统或者其他信息吗
> > 
> > 
> > 就在windows安装： go install github.com/wailsapp/wails/v2/cmd/wails@latest报错呢
> 
> 是不是你的Go的版本问题，用go get试试

果然是我的go版本问题

**Comment by timetravel-boy** [comment]
![image](https://github.com/qiwentaidi/Slack/assets/80373498/42f7f5a7-58c1-401b-be2e-211a8d4f9be2)
新问题，编译报错

**Comment by qiwentaidi** [comment]
在常见问题哪里找一下，cgo模式没开启
