### ISSUE TITLE
Mac系统下选中字典功能无法加载

### ISSUE THREAD

**Issue by LztCode** [qiwentaidi/Slack#8]
1、mac版本的子域名暴破模块，选择子域字典的时候报错，没办法选择字典
slack-wails_darwin_arm64[52804:19240032] +[CATransaction synchronize] called within transaction
<img width="860" alt="image" src="https://github.com/qiwentaidi/Slack/assets/73683679/45cb1bd0-b17c-422d-83d0-72423ccb9a3c">
<img width="984" alt="image" src="https://github.com/qiwentaidi/Slack/assets/73683679/b3b98b15-9e5a-4102-8877-cea456101aa6">

**Comment by LztCode** [comment]
> 看下是不是版本下错了
换了 amd64 版本还是报错
<img width="971" alt="image" src="https://github.com/qiwentaidi/Slack/assets/73683679/68aa2c1c-925e-4230-b093-6a7537395bfa">

**Comment by qiwentaidi** [comment]
我用了mac m2 的系统测试是能正常的使用的，是不是电脑有些配置错误，我觉得不是程序的问题

**Comment by cream-sec** [comment]
子域名爆破，遇到同样的问题，无法添加字典

**Comment by qiwentaidi** [comment]
> 子域名爆破，遇到同样的问题，无法添加字典

也是mac arm版出现的问题吗

**Comment by qiwentaidi** [comment]
可以在mac上复现，目前在测试是否是mac版本问题导致

**Comment by qiwentaidi** [comment]
已找到解决方案，通过使用wails自带的文件选择器可以解决该问题

**Comment by qiwentaidi** [comment]
自带的dialog仅在某些macos的版本上生效，待定，由于本人不是mac系统，调试这个适配很麻烦，准备暂时用内置字典代替文件选择功能

**Comment by qiwentaidi** [comment]
> 1、mac版本的子域名暴破模块，选择子域字典的时候报错，没办法选择字典 slack-wails_darwin_arm64[52804:19240032] +[CATransaction synchronize] called within transaction <img alt="image" width="860" src="https://private-user-images.githubusercontent.com/73683679/293856808-45cb1bd0-b17c-422d-83d0-72423ccb9a3c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ2OTMyODksIm5iZiI6MTcwNDY5Mjk4OSwicGF0aCI6Ii83MzY4MzY3OS8yOTM4NTY4MDgtNDVjYjFiZDAtYjE3Yy00MjJkLTgzZDAtNzI0MjNjY2I5YTNjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA4VDA1NDk0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAyMzYwN2NlMzExYjk1ZmMwMTUzY2ZmZTQ2ZjBmZWZmOWQzNzMxODE4Y2E5MWIzOTBjYzUyNDRiZjU1NTk0NzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LeL5rtk97bAyTtNvuUpPBbCR6ANNOCtFXl7jAmrMddQ"> <img alt="image" width="984" src="https://private-user-images.githubusercontent.com/73683679/293856615-b3b98b15-9e5a-4102-8877-cea456101aa6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ2OTMyODksIm5iZiI6MTcwNDY5Mjk4OSwicGF0aCI6Ii83MzY4MzY3OS8yOTM4NTY2MTUtYjNiOThiMTUtOWU1YS00MTAyLTg4NzctY2VhNDU2MTAxYWE2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA4VDA1NDk0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdlZmMzNDM0YzZlM2Q4NGI2MDY4MDYzNDgwNTE2NTc4MjgwOTFhZDE5MmMwYmU4MWNhMDY5ZDRiZWYwMjcxZGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.naYl_PjLs-BiADpTWwtdsDsx8npLO9YD0eVp8-Kh3GM">

方便提供一下wails doctor的信息吗

**Comment by LztCode** [comment]
> > 1、mac版本的子域名暴破模块，选择子域字典的时候报错，没办法选择字典 slack-wails_darwin_arm64[52804:19240032] +[CATransaction synchronize] called within transaction <img alt="image" width="860" src="https://private-user-images.githubusercontent.com/73683679/293856808-45cb1bd0-b17c-422d-83d0-72423ccb9a3c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ2OTMyODksIm5iZiI6MTcwNDY5Mjk4OSwicGF0aCI6Ii83MzY4MzY3OS8yOTM4NTY4MDgtNDVjYjFiZDAtYjE3Yy00MjJkLTgzZDAtNzI0MjNjY2I5YTNjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA4VDA1NDk0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAyMzYwN2NlMzExYjk1ZmMwMTUzY2ZmZTQ2ZjBmZWZmOWQzNzMxODE4Y2E5MWIzOTBjYzUyNDRiZjU1NTk0NzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LeL5rtk97bAyTtNvuUpPBbCR6ANNOCtFXl7jAmrMddQ"> <img alt="image" width="984" src="https://private-user-images.githubusercontent.com/73683679/293856615-b3b98b15-9e5a-4102-8877-cea456101aa6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ2OTMyODksIm5iZiI6MTcwNDY5Mjk4OSwicGF0aCI6Ii83MzY4MzY3OS8yOTM4NTY2MTUtYjNiOThiMTUtOWU1YS00MTAyLTg4NzctY2VhNDU2MTAxYWE2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA4VDA1NDk0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdlZmMzNDM0YzZlM2Q4NGI2MDY4MDYzNDgwNTE2NTc4MjgwOTFhZDE5MmMwYmU4MWNhMDY5ZDRiZWYwMjcxZGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.naYl_PjLs-BiADpTWwtdsDsx8npLO9YD0eVp8-Kh3GM">
> 
> 方便提供一下wails doctor的信息吗
<img width="661" alt="image" src="https://github.com/qiwentaidi/Slack/assets/73683679/9fc3f354-ef29-454f-b12c-62fd20049112">

**Comment by qiwentaidi** [comment]
![image](https://github.com/qiwentaidi/Slack/assets/104491549/3e618c67-7ac9-49b6-8cd6-53ea562e6387)
通过其他方式暂时缓解这个问题

**Comment by qiwentaidi** [comment]
> ![image](https://private-user-images.githubusercontent.com/104491549/295458487-3e618c67-7ac9-49b6-8cd6-53ea562e6387.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ4NjUwNDUsIm5iZiI6MTcwNDg2NDc0NSwicGF0aCI6Ii8xMDQ0OTE1NDkvMjk1NDU4NDg3LTNlNjE4YzY3LTdhYzktNDliNi04Y2Q2LTUzZWE1NjJlNjM4Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExMFQwNTMyMjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NzIzMGQxYjRkZmY0N2UxZjcwZDQ5YmI5OGEyYWViOGU1MmVjOWZhMDI1YTRmZTNkYzY3OWFlMWZjOGFhYWUzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.GFgeDrIWLOzNKDDyIJbX_c6ndU8SAg1wZ9csHEth9us) 通过其他方式暂时缓解这个问题

目前会和目录扫描一样加载一个默认字典

**Comment by qiwentaidi** [comment]
`Wails Doctor

# Wails
Version | v2.7.1

# System
┌─────────────────────────┐
| OS           | MacOS    |
| Version      | 14.3     |
| ID           | 23D56    |
| Go Version   | go1.21.6 |
| Platform     | darwin   |
| Architecture | arm64    |
| CPU          | Unknown  |
| GPU          | Unknown  |
| Memory       | Unknown  |
└─────────────────────────┘

# Dependencies
┌────────────────────────────────────────────────────────────────┐
| Dependency                | Package Name | Status    | Version |
| Xcode command line tools  | N/A          | Installed | 2405    |
| Nodejs                    | N/A          | Installed | 20.11.0 |
| npm                       | N/A          | Installed | 10.2.4  |
| *Xcode                    | N/A          | Available |         |
| *upx                      | N/A          | Available |         |
| *nsis                     | N/A          | Available |         |
└─────────────────── * - Optional Dependency ────────────────────┘

# Diagnosis
Optional package(s) installation details:
  - Xcode: Available at https://apps.apple.com/us/app/xcode/id497799835
  - upx : Available at https://upx.github.io/
  - nsis : More info at https://wails.io/docs/guides/windows-installer/

 SUCCESS  Your system is ready for Wails development!

 ♥   If Wails is useful to you or your company, please consider sponsoring the project:
https://github.com/sponsors/leaanthony`

<img width="1469" alt="image" src="https://github.com/qiwentaidi/Slack/assets/104491549/3816517a-2d98-4066-ab8d-d00ac68a19c1">
测试在新版macos14.3中可以正常使用该功能

**Comment by qiwentaidi** [comment]
> 1、mac版本的子域名暴破模块，选择子域字典的时候报错，没办法选择字典 slack-wails_darwin_arm64[52804:19240032] +[CATransaction synchronize] called within transaction <img alt="image" width="860" src="https://private-user-images.githubusercontent.com/73683679/293856808-45cb1bd0-b17c-422d-83d0-72423ccb9a3c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcxNTA1MTMsIm5iZiI6MTcwNzE1MDIxMywicGF0aCI6Ii83MzY4MzY3OS8yOTM4NTY4MDgtNDVjYjFiZDAtYjE3Yy00MjJkLTgzZDAtNzI0MjNjY2I5YTNjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA1VDE2MjMzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA5ZmMwYzFjMzA3ZGRkYjgyODNkMDgwYWU3MWIyZjljYWE4NzZiYmY1YzQ0ODg0MmExOTJiYzFkMWRlMWFiMGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VtsnZF3C-r_uKEAf0FRDIzjEvmqW8USE2kIhJ91RVZo"> <img alt="image" width="984" src="https://private-user-images.githubusercontent.com/73683679/293856615-b3b98b15-9e5a-4102-8877-cea456101aa6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcxNTA1MTMsIm5iZiI6MTcwNzE1MDIxMywicGF0aCI6Ii83MzY4MzY3OS8yOTM4NTY2MTUtYjNiOThiMTUtOWU1YS00MTAyLTg4NzctY2VhNDU2MTAxYWE2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA1VDE2MjMzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNhODY5MjY4Yzk1MWI4MzRiYjhlMmI0MTUzNzZiOTM4ODY3ZjMxZTczZGEyMDZkNjZmN2RhYWJlMzI3YWI1YmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.puL51R7EpnXiwqnmPFHSkdWpJOx_2gpNk_V5plRS1QA">

有空可以麻烦测试一下新版本能否打开选择字典功能吗，如果正常的话可能就是编译主机系统版本问题，没问题的我话我就可以关闭这个issue

**Comment by LztCode** [comment]
> > 1、mac版本的子域名暴破模块，选择子域字典的时候报错，没办法选择字典 slack-wails_darwin_arm64[52804:19240032] +[CATransaction synchronize] called within transaction <img alt="image" width="860" src="https://private-user-images.githubusercontent.com/73683679/293856808-45cb1bd0-b17c-422d-83d0-72423ccb9a3c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcxNTA1MTMsIm5iZiI6MTcwNzE1MDIxMywicGF0aCI6Ii83MzY4MzY3OS8yOTM4NTY4MDgtNDVjYjFiZDAtYjE3Yy00MjJkLTgzZDAtNzI0MjNjY2I5YTNjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA1VDE2MjMzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA5ZmMwYzFjMzA3ZGRkYjgyODNkMDgwYWU3MWIyZjljYWE4NzZiYmY1YzQ0ODg0MmExOTJiYzFkMWRlMWFiMGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VtsnZF3C-r_uKEAf0FRDIzjEvmqW8USE2kIhJ91RVZo"> <img alt="image" width="984" src="https://private-user-images.githubusercontent.com/73683679/293856615-b3b98b15-9e5a-4102-8877-cea456101aa6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcxNTA1MTMsIm5iZiI6MTcwNzE1MDIxMywicGF0aCI6Ii83MzY4MzY3OS8yOTM4NTY2MTUtYjNiOThiMTUtOWU1YS00MTAyLTg4NzctY2VhNDU2MTAxYWE2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA1VDE2MjMzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNhODY5MjY4Yzk1MWI4MzRiYjhlMmI0MTUzNzZiOTM4ODY3ZjMxZTczZGEyMDZkNjZmN2RhYWJlMzI3YWI1YmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.puL51R7EpnXiwqnmPFHSkdWpJOx_2gpNk_V5plRS1QA">
> 
> 有空可以麻烦测试一下新版本能否打开选择字典功能吗，如果正常的话可能就是编译主机系统版本问题，没问题的话就可以关闭这个issue

多谢，已经可以正常选择字典了，我有个小小的建议就是这个爆破进度条尽量用浅色，蓝色有点刺眼
