### ISSUE TITLE
非常nice的学习项目

### ISSUE THREAD

**Issue by onewinner** [qiwentaidi/Slack#9]
之前就学习了大佬Fyne的项目，自己一直想着用wails开发一套类似的，没想到大佬项目就出来了，太赞了很不错的学习项目、最近看到tidesec也放出来一个wails开发的类似项目界面写的挺漂亮的，不过不是开源的，大佬也可以参考参考它的一些几面功能方面，完善一下https://github.com/TideSec/TscanPlus

**Comment by qiwentaidi** [comment]
确实是个不错的项目，感觉右键联动功能和指纹显示比较值得先参考，还有什么其他你觉得不错的点也可以说一下

**Comment by xulei131401** [comment]
大佬，抽空给个github actions打包的例子呗？这个项目是如何打包编译的

**Comment by qiwentaidi** [comment]
> 大佬，抽空给个github actions打包的例子呗？这个项目是如何打包编译的

不好意思才看到消息，
windows环境下打包，请安装mingw64 gcc环境变量，以及wails + nodejs + go + npm 环境，装完之后到进入到代码主目录执行wails build即可

**Comment by arkizat** [comment]
初始化指纹规则失败，请检查配置文件
最新版本下载运行时候报这样 ,这个怎么解决

**Comment by qiwentaidi** [comment]
> 初始化指纹规则失败，请检查配置文件 最新版本下载运行时候报这样 ,这个怎么解决

参考[issues17](https://github.com/qiwentaidi/Slack/issues/17)

**Comment by arkizat** [comment]
> > 初始化指纹规则失败，请检查配置文件 最新版本下载运行时候报这样 ,这个怎么解决
> 
> 参考[issues17](https://github.com/qiwentaidi/Slack/issues/17)

好的 谢谢你
